### ISSUE TITLE
The version is greater than and equal to, not equal to.

### ISSUE THREAD

**Issue by krotesk** [HewlettPackard/python-redfish-utility#104]
In line https://github.com/HewlettPackard/python-redfish-utility/blob/f88c6fa490487e4be027a755690927f94a0421d3/setup.py#L6
```
==> Запускается package()...
error in ilorest setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
    python-ilorest-library >= "4.8.0.0"
                           ^
==> ОШИБКА: Произошел сбой в package().
    Прерывание...
```
The version should be greater than and equal to, not equal to. The current version of python-ilorest-library is 5.3.0.0 and will not install with it.

**Comment by krotesk** [comment]
https://github.com/HewlettPackard/python-redfish-utility/blob/f88c6fa490487e4be027a755690927f94a0421d3/setup.py#L51
```
error in ilorest setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
    python-ilorest-library >= "4.8.0.0"
```
the comparison version should be without quotes!
`python-ilorest-library >= 4.8.0.0`

**Comment by rajeevkallur** [comment]
fixed
