### ISSUE TITLE
Bootorder command doesn't change the bootorder

### ISSUE THREAD

**Issue by bilalasd** [HewlettPackard/python-redfish-utility#12]
This is the command I tried

bootorder [2,4] --commit

The above command throws this error "Setting for 'persistentbootconfigorder' is the same as the current value."

I have changed '[2,4] to many different values and the output is always the above.

I have tried it both in interactive mode and in script

thanks,

**Comment by Yergidy** [comment]
@bilalasd Can you retry with the latest release. iLOrest 2.4.1 and see if that solves your issue?

**Comment by sahanaramavana** [comment]
Hi @bilalasd ,

Kindly check this on iLORest 3.3.0 released version of our tool .  We couldn't see this error on this version locally . 

Thanks & Regards,
Sahana
