### ISSUE TITLE
Doc Update: createlogicaldrive Example Command

### ISSUE THREAD

**Issue by sw-elling** [HewlettPackard/python-redfish-utility#15]
The custom logical drive creation example in the [RESTful Interface Tool User Guide](https://hewlettpackard.github.io/python-redfish-utility/#createlogicaldrive-command) is invalid.

The example given lists the drive with an index of 2 in both the list of physical drive indexes and in the "--spare-drives" option:

```
iLOrest > login
Discovering data...Done
ilorest > createlogicaldrive customdrive Raid5 2,3,4,5,6 --controller=1 --name=ANewLogicalDrive --spare-drives=2 --capacityGiB=100 --legacy-boot=Primary --accelerator-type=ControllerCache --sparetye=Dedicated
```
Testing shows that the designated spare drive must not be in the list of physical drive indexes.

----
The tool's built in documentation w.r.t. custom logical drive creation can use some polishing.

```
ilorest --nologo help createlogicaldrive
```
> To create a custom logical drive.
>         example: createlogicaldrive customdrive <raid-level> <physicaldriveindex(s)> --name=drivename --spare-drives=3,4 --spare-type=Dedicated --capacityGiB=10 --acc
> elerator-type=None
> 

The "_--spare-drives=3,4_" option in the example should probably be "--spare-drives=<physicaldriveindex(es)>" or similar.

In addition, clarification should be provided:
* The "physicaldriveindex(es)" must be a comma separated list for both the drives that make up the logical drive and the spares
* The spare drive index(es) cannot be listed on the physical drive indexes

**Comment by Yergidy** [comment]
Thank you for the find and report. We will update the documentation to fix this.

**Comment by sw-elling** [comment]
I'm no longer supporting HPE hardware so do what you want with this issue.

**Comment by rajeevkallur** [comment]
Fixed
