### ISSUE TITLE
serverclone load generates "Unable to remove property 'Enabled'.\n" in clone_error_logfile.log

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#16]
When submitting the ilorest serverclone load -f EthernetInterface.txt command with the attached file, errors are generated in clone_error_logfile.log:

["Unable to remove property 'Enabled'.\n", "Unable to remove property 'Enabled'.\n"]

I suspect those errors come from property Enabled=<boolean> in Oem/Hpe/DHCPv4 visible at lines 41 and 210 in file EthernetInterface.txt

However, the PATCH requests generated by this load command return a 200/Ok response visible in lines 805 and 2321 of file EthernetInterface-debug.txt. Hence I suspect they are not harmful but customer is confused...

[clone_error_logfile.log](https://github.com/HewlettPackard/python-redfish-utility/files/3222201/clone_error_logfile.log)

[EthernetInterface.txt](https://github.com/HewlettPackard/python-redfish-utility/files/3222210/EthernetInterface.txt)
[EthernetInterface-debug.txt](https://github.com/HewlettPackard/python-redfish-utility/files/3222213/EthernetInterface-debug.txt)

**Comment by Yergidy** [comment]
Can you please retry with the latest version and see if this issue is resolved?

**Comment by sahanaramavana** [comment]
Hi @donzef ,

Kindly let us know whether the issue is reproducible in our latest released version of the tool .

Thanks & Regards,
iLORest Team

**Comment by donzef** [comment]
Could not reproduce with 3.5.1.0
