### ISSUE TITLE
ILOREST How add ISCSI BOOT Attempts

### ISSUE THREAD

**Issue by DietzCJ** [HewlettPackard/python-redfish-utility#17]
iscsiconfig --add [1]
iscsiconfig --add [2]
iscsiconfig --add [3]
iscsiconfig --add [4]
It will only add 3 and 4.
"Failed to add NIC. All NICs have already been configured."
I know I can add them manually, then Iscsiconfig --list -f c:\output.txt
Then modify, but how can you create them programmatically ?

**Comment by Yergidy** [comment]
You can only have 4 attempts, so if you have any attempts already on the system before running those commands it will fail when it has filled up all attempts.

Currently the only way to modify an iscsi boot attempt is to modify the output file. The current programmatic way would be to open the file and modify it in a script.

We are open to making this command easier to use without a file in the future.
