### ISSUE TITLE
serverclone fails to load EthernetInterface when IPv4StaticAddress or SubnetMask is identical to existings

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#18]
If I try to serverclone load only the Dedicated iLO NIC IPv4 Static Address, keeping the SubnetMask and Gateway as what is already configured, the PATCH request returns a "400 Bad request" with error PropertyValueRequired: ["IPv4Addresses","SubnetMask"].

If I try to serverclone load only the SubnetMask of the Dedicated iLO network port, keeping the IPv4StaticAddress and Gateway as what it is already configured, the PATCH request returns the error: PropertyValueRequired: ["IPv4Addresses","IPv4Address"].

Example: the Dedicated iLO port is configured with:

"IPv4StaticAddresses": [
        {
          "Address": "172.16.50.99",
          "SubnetMask": "255.255.**255**.0",
          "Gateway": "172.16.50.254"
        }
      ]

If the serverclone load file contains the following to modify only the SubnetMask:
"IPv4StaticAddresses": [
        {
          "Address": "172.16.50.99",
          "SubnetMask": "255.255.**252**.0",
          "Gateway": "172.16.50.254"
        }
      ]
Then the above error occurs.

In debug mode, I noticed that the load command removes all the attributes that are identical to the current ones. Unfortunately, IPv4Address and SubnetMask must be present in the PATCH request. 

N

**Comment by Yergidy** [comment]
Can you please retry with the latest version and see if this issue is resolved?

**Comment by sahanaramavana** [comment]
Hi @donzef ,

Kindly let us know whether this issue is seen in our latest released version of iLORest Tool which is available. 

Thanks & Regards,
iLORest Team

**Comment by donzef** [comment]
Could not reproduce with 3.5.1.0
