### ISSUE TITLE
InBand with serverclone does not reset iLO when it should

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#19]
The following problem occurs only in InBand Management with serverclone load.

When modifying the IPv4StaticAddress array with serverclone load in In-Band mgmt, the system is reset, but not the iLO. Hence the modifications are not taken into account.

See the sequence in attached file.
![InBand-ServerClone](https://user-images.githubusercontent.com/42031605/60813737-9e06fa80-a194-11e9-8b04-3b6a2e27da98.jpg)

**Comment by Yergidy** [comment]
Can you please retry with the latest version and see if this issue is resolved?

**Comment by donzef** [comment]
Could not reproduce. Closing.
