### ISSUE TITLE
Still seeing relinking issue in 2.5.0

### ISSUE THREAD

**Issue by wookieboy** [HewlettPackard/python-redfish-utility#20]
I have installed version 2.5.0-22 to replace version 2.41 on CentOS 7 and I am still getting this same error message.

Cannot open self /usr/sbin/ilorest or archive /usr/sbin/ilorest.pkg

I have tried creating the file /etc/prelink.conf.d/ilorest.conf  
with the contents -b /usr/sbin/ilorest
After creating the file I ran the prelink command manually, and even deleted the cache file and ran the cron job. It is still showing this same error message once the .rpm has been installed for a while. It seems like it is fixed when freshly installed but once prelink breaks it I do not have a good work around other than remove, reinstall.

**Comment by wookieboy** [comment]
Just to update I did get the conf file to finally work. I had to uninstall the rpm, reinstall the rpm, create the exclusion file, run the cron job for prellink, and then the executable will work for 2.5.0 Is there any way to get this recompiled with whatever is causing prelink to break this binary?

**Comment by Yergidy** [comment]
Unfortunately until pyinstaller fixes the prelinking issue on their end we cannot support it fully. There are some workarounds  when we build that may stop the binary from breaking when prelinking is enabled. We hope to have those in next release, if they work, so these workarounds are not required by the user.

**Comment by Yergidy** [comment]
For reference the pyinstaller issue is here: https://github.com/pyinstaller/pyinstaller/issues/3441

**Comment by Yergidy** [comment]
It looks like there is a pyinstaller PR to fix this in review right now. We will use the pyinstaller with the fix once it is released. 

PR for reference: https://github.com/pyinstaller/pyinstaller/pull/4450

**Comment by sahanaramavana** [comment]
Hi @wookieboy ,

Kindly perform the check on our latest released version of tool, which is iLORest 3.3 .

If you still see issue let us know. 

Thanks & Regards,
iLORest Team
