### ISSUE TITLE
Ilorest.exe: error when trying to mark IML entry repaired

### ISSUE THREAD

**Issue by msroedel** [HewlettPackard/python-redfish-utility#23]
When trying to mark an IML entry repaired on a ILO4 2.73 the following error occurs: 
Command:
`.\ilorest.exe serverlogs --selectlog=IML --repair 8  (also tried -r )

.\ilorest.exe : iLO response with code [400]: An unknown property is in the request body.
At C:\Scripts\ResetIML.ps1:26 char:1
+ .\ilorest.exe serverlogs --selectlog=IML --repair $entry.Id
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (iLO response wi...e request body.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError`

**Comment by sahanaramavana** [comment]
Hi @msroedel ,

The fix will be available in our next build ilorest 4.0.0.0.

Thanks & Regards,
iLORest Team

**Comment by rajeevkallur** [comment]
Already 4.0 is available and released
