### ISSUE TITLE
Doc and Help message update: --cache-dir requires a "=" sign before argument

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#28]
ilorest help a well as associated documentation specifies :
 --cache-dir PATH 

This misleading. It should say:

--cache-dir=PATH

![image](https://user-images.githubusercontent.com/42031605/88192687-1e33bd00-cc3d-11ea-844b-da288af7f932.png)
![image](https://user-images.githubusercontent.com/42031605/88193584-1f191e80-cc3e-11ea-9ef4-d094821b03c5.png)

Thanks

**Comment by KeepSummerSaf3** [comment]
Agreed. Will note for update in the help at the release of 3.2.0 and in the documentation asap.

**Comment by rajeevkallur** [comment]
Fixed
