### ISSUE TITLE
Unable to set CSR_CommonName via ilorest certificate csr

### ISSUE THREAD

**Issue by localleon** [HewlettPackard/python-redfish-utility#30]
Greetings,

i can't seem to get the csr generating process to work with the ilorest cli. It always throws an error that my CommonName is not defined. The help message of the `certificate csr` command only tells me to put other Arguments, it wont accept a CN. 

What do i need to do to define the CommonName. `set csr_commonname=VALUE` throws the error `Same as the current value`

Followed all the steps in the Documentation under https://hewlettpackard.github.io/python-redfish-utility/#backuprestore-command

Real Output: 
```
iLOrest > login
Discovering data...Done
iLOrest > certificate csr "Hewlett Packard Enterprise" "iLORest Group" CName "United States" Texas Houston 
ERROR: global name "csr_commonname" is not defined
```

Expected Output: 
```
iLOrest > login
Discovering data...Done
iLOrest > certificate csr "Hewlett Packard Enterprise" "iLORest Group" CName "United States" Texas Houston 
iLO is creating a new certificate signing request This process can take up to 10 minutes.
X509 Certificate is being generated and the process might take up to 10 minutes.
```

Tried on a ilo4 V 2.60

Kind Regards,
localleon

**Comment by rajeevkallur** [comment]
This will be fixed in the soon to be released 3.1.1 version.
![image](https://user-images.githubusercontent.com/21117913/98098754-c1d76f00-1eb4-11eb-9632-2a6883850967.png)
