### ISSUE TITLE
save command does not accept --filter in interactive mode

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#33]
As per the `save` help, --filter is an option. Supplying --filter in script mode works fine. However, an error is returned in interactive mode. 

iLOrest version: 3.1.1

![image](https://user-images.githubusercontent.com/42031605/105042660-c7c8ff00-5a64-11eb-8d4f-cd04f6f2ec43.png)

![image](https://user-images.githubusercontent.com/42031605/105042917-20989780-5a65-11eb-9847-8b4222cb3d5f.png)

**Comment by sahanaramavana** [comment]
Hi @donzef ,

Issue fix will be available in iloRest release 3.6.0.0 .

Thanks & Regards,
Sahana

**Comment by rajeevkallur** [comment]
working in latest ilorest 4.0 which is available and published
