### ISSUE TITLE
ilorest serverclone requires lot of effort 

### ISSUE THREAD

**Issue by ygiri1** [HewlettPackard/python-redfish-utility#36]
Hi Team,

i recently used iloreset serverclone saved all the changes applied to server001 and when did change required fields like IP address and Hostname and ILO License. I didn't know it would even change the serial number. In fact serial number is a unique property to every other server. why serverclone is updating such property when its never required. 

and in the json file have already updated the autoneg and Full Duplex with Boolean values. I don't know why I got this message.

Patching '#Manager.v1_5_1.Manager'.
Loading configuration...
Committing changes...
The operation completed successfully.
"AutoNeg" requires Property "SpeedMbps+FullDuplex" to be specified.

in IPV4, there was 2 area need to update the IP Address, Subnet Mask, and Gateway. like which one needs to be updated exactly.

/redfish/v1/Managers/1/EthernetInterfaces/IPv4Addresses
/redfish/v1/Managers/1/EthernetInterfaces/IPv4StaticAddresses

**Comment by rajeevkallur** [comment]
We will investigate this and get back to you.

**Comment by sahanaramavana** [comment]
Hi @ygiri1 ,

Have you verified the same on the released version of our tool which is 3.5.1 . 

kindly let us know if you are seeing serial number getting overridden, because unless we use the flag uniqueoverride it wouldnt be overriding the system specific values. 

Thanks & Regards,
iLORest Team

**Comment by rajeevkallur** [comment]
Please use --uniqueoverride along with serverclone command as serialnumber is unique. Documentation for this is available below
https://hewlettpackard.github.io/python-redfish-utility/#serverclone-command
