### ISSUE TITLE
ServerClone Stop Auto Restart

### ISSUE THREAD

**Issue by jjwb96** [HewlettPackard/python-redfish-utility#37]
Hi there,

I am automating the deployment of Server 2019 using SCCM on to about 30 HPE Proliant MicroServer Gen 10Plus. When I use the serverclone load --auto option it just reboots the server when it finishes applying my custom json. Is there any way to stop it from rebooting the server? I have a reboot task that comes after applying my custom json. However it doesn't get to the reboot task since the application initiates the restart. 

Is there a better way to accomplish what I am trying to do? Without the --auto option it freezes the OSD since the program requires input from the user to accept the changes. 

Just looking for the best way to accomplish this. 

Thanks in advance!

**Comment by jjwb96** [comment]
I am trying to figure out how to add this, however, I am noticing config.rdmc_config and six.moves cannot be found. Wondering what I need to do to get it working. 
![image](https://user-images.githubusercontent.com/58758300/121199949-56d28a00-c841-11eb-8448-48e867d4d64b.png)

**Comment by rajeevkallur** [comment]
We will investigate and probably we will add a separate option for the reboot in the next version of ilorest tool.

**Comment by jjwb96** [comment]
@rajeevkallur Is it possible to get a copy of the config.rdmc_config module uploaded to the GitHub Repo so I can add it myself?

**Comment by rajeevkallur** [comment]
It is uploaded now.

**Comment by jjwb96** [comment]
Thank you!

**Comment by jjwb96** [comment]
@rajeevkallur It appears the EthernetCommand.py module is missing. ServerClone errors out with the following error:
![image](https://user-images.githubusercontent.com/58758300/121390160-1ba48980-c91b-11eb-8f84-a53292fa29eb.png)

**Comment by rajeevkallur** [comment]
Added

**Comment by sahanaramavana** [comment]
Hi @jjwb96 ,

1. --auto is designed to perform the actions silently , so by design it would reboot as well ,as some of the settings for them to take effect its important to reboot . And since we are in auto mode it will automatically reboot
2. In the latest released version of the iLORest tool which is 3.3.0 , we did check and we are able to get the help file for serverclone. 

Thanks & Regards,
iLORest Team

**Comment by sahanaramavana** [comment]
Hi @jjwb96 ,

We are planning to add a --restart filter in future to facilitate the selective reboot option . 

Thanks for your cooperation . 

Thanks & Regards,
iLORest Team
