### ISSUE TITLE
Error 405 -- Method Not Allowed

### ISSUE THREAD

**Issue by tdeneau** [HewlettPackard/python-redfish-utility#4]
Not sure if this is appropriate for this project and it may be more of an HP DL360 question but...

I am trying to use Redfishtool (https://github.com/DMTF/Redfishtool) to change a BIOS setting on an HP DL360.  I am using the same general technique that I used on other Redfish implementations (like supermicro) and it worked fine there.

python3 redfishtool.py -r ilomxq61101ng -u name -p password raw PATCH  -d '{"ProcHyperthreading": "Disabled"}' /redfish/v1/systems/1/bios

but on the DL360 this gives:
   redfishtool: Transport: Response Error: status_code: 405 -- Method Not Allowed

Should I be able to change a BIOS setting in this way?

**Comment by tdeneau** [comment]
Yes things work on bios/settings URI.  A question from someone new to Redfish...  For those implementations that actually do support PATCHing the Bios settings, will the exact URI always be implementation-dependent?

**Comment by Yergidy** [comment]
@tdeneau It is advised to work using types as URIs are subject to change while types have versioning attached that can be monitored. However, I believe it is redfish standard to have bios setting be changed using the ~/bios/settings URI.

**Comment by Yergidy** [comment]
Closing this issue if there are no further questions.
