### ISSUE TITLE
Set Bootable Device(s) for Legacy Boot Mode > Number of OS bootable drives 

### ISSUE THREAD

**Issue by zejdlikt** [HewlettPackard/python-redfish-utility#44]
Hello, is there a way to setup a "nuber of OS bootable drives" using ilorest utility?

As per manual, it's possible to do it in bios gui:

```
Setting the number of OS bootable drives (Legacy Boot Mode)
Procedure

    From the System Utilities screen, select System Configuration > controller > Set Bootable Device(s) for Legacy Boot Mode > Number of OS bootable drives.
    In the Number of OS bootable drives screen, specify the number of OS bootable drives.
    Click Submit Changes.
```
Thank you

**Comment by sahanaramavana** [comment]
Hi @zejdlikt ,

Kindly try whether bootorder command helps with this . 
below is the documentation guide to help with usage . 

https://hewlettpackard.github.io/python-redfish-utility/#bootorder-command

Thanks & Regards,
iLORest Team
