### ISSUE TITLE
V3.2.2 and higher don't prompt for password on login

### ISSUE THREAD

**Issue by firthmj** [HewlettPackard/python-redfish-utility#47]
In V3.2.1 and older, if you try and login to a remote ILO with just a username, then it will prompt for a password, meaning it isn't necessary to type the password in clear text to the "-p" option.

In V3.2.2 and newer, it seems that it no longer does this, and just fails to login.

Is this a regression, or is there some other way to get newer versions to prompt for the password?

**Comment by rajeevkallur** [comment]
@firthmj Will check and let you know

**Comment by sahanaramavana** [comment]
Hi @firthmj ,

This fix is available in our upcoming release of iLORest 4.0.0.0 version which is scheduled to match with gen 11 server timeframe.

Thanks & Regards,
iLORest Team

**Comment by rajeevkallur** [comment]
Fixed
