### ISSUE TITLE
ilorest createlogicaldrive based on drive size or Model?

### ISSUE THREAD

**Issue by ralfgro** [HewlettPackard/python-redfish-utility#48]
I really tried hard to understand, but I failed. How can I create a Raid1 with devices of a certain size?

# ilorest createlogicaldrive quickdrive Raid1 2 SSD SATA Internal --controller=0
# ilorest createlogicaldrive customdrive Raid1 1I:3:2,1I:3:1 SAS --controller=0 

This worked for me and is fine for ESXi servers with only 2 local drives, or if I know the index/location. But we have servers with drives used for datastores. Usually they are different in size. 

So how can user drives by type or size or index?

# ilorest smartarray --physicaldrives
Discovering data...Done
Controllers:
[0]: Slot 0 - HPE Smart Array E208i-a SR Gen10
        Physical Drives:
        [1I:3:2]: Model VK000480GWTTA, Location 1I:3:2, Type SSD, Serial xxxx - 457862 MiB
        [1I:3:1]: Model VK000480GWTTA, Location 1I:3:1, Type SSD, Serial xxxx - 457862 MiB

**Comment by rajeevkallur** [comment]
@ralfgro ,  it is smartarray controller which is doing this work in the background.  If the drives are of different size, RAID 1 will be created using smaller drive size.  The controller will apply all RAID rules whether it is raid 0, raid1 , raid5, raid10 etc...  You can try the command in the intended server and let us know the outcome.
