### ISSUE TITLE
How to disable the SD Card slot using command line?

### ISSUE THREAD

**Issue by sloppyhead** [HewlettPackard/python-redfish-utility#49]
I am able to retrieve the SD card slot status with the command  
 "ilorest get Controller/Status/State --selector=EmbeddedMedia"

How do I disable the SD card slot using command line?

**Comment by fmoreno-nj** [comment]
ilorest set  InternalSDCardSlot=Disabled --selector=Bios.

**Comment by sahanaramavana** [comment]
Hi @sloppyhead ,

Here is the set of commands 
ilorest -v set InternalSDCardSlot=Disabled --selector=Bios.

ilorest -v commit

ilorest -v reboot

Thanks & Regards,
iLORestTeam
