### ISSUE TITLE
ilorest deletelogicaldrive return Missing token required for operation. Please add the proper token

### ISSUE THREAD

**Issue by Sharkrit** [HewlettPackard/python-redfish-utility#5]
Hi HPE,

I want to wipe all existing logicaldrive but I have got errors as below:

`ilorest deletelogicaldrive --all --force --controller=1 --url ilo_ip_address -u myusername -p mypassword`

`iLOrest : RESTful Interface Tool version 2.2`
`Copyright (c) 2014, 2017 Hewlett Packard Enterprise Development LP`
`--------------------------------------------------------------------------------`
`Discovering data...Done`
`WARNING: Cache is activated. Session keys are stored in plaintext.`
`Missing token required for operation. Please add the proper token.`
`"Ex: biospassword flag if bios password present or tpmenabled flag if TPM module present"`

Can you please help me troubleshooting this?

**Comment by Yergidy** [comment]
@Sharkrit This error signifies the currently logged in iLO account does not have the proper privilege to perform storage operations. Make sure the iLO account being used has the "Host Storage" privilege.

**Comment by talamoig** [comment]
@Yergidy I also get the same error with a user created via HPONCFG with admins priviledges. 
Is it possible to add the "Host Storage" priviledges via the ilorest?

**Comment by talamoig** [comment]
For who may need, the command to use from the ilorest prompt is:
```
set --filter UserName=username Oem/Hpe/Privileges/HostStorageConfigPriv=True
```

**Comment by Yergidy** [comment]
Closing this issue. Please reopen if needed.
