### ISSUE TITLE
Enhancement: Add a `delete` sub-command to the `ilolicense` iLO macro command

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#50]
Seen a request for deleting a license in [Slack](https://hpe-internal.slack.com/archives/C02EPJFQ8PL/p1649369857722899). 

It could be nice to be able to perform this operation with iLOrest. Something like:

`ilorest ilolicense delete 1`  where `1` is the Id of the license to delete.

Thanks,
François

**Comment by rajeevkallur** [comment]
we will check this.

**Comment by donzef** [comment]
Thanks. 

I just noticed that using `ilolicense` with no argument lists the properties of the installed licenses (not formerly mentioned in the doc!). Since the `Id` property may be different from the `{item}` of the `@data.id` property, it would be good to print as well the `@data.id` of the installed licenses. Something like:

`ilorest ilolicense`
`@data.id: /redfish/Managers/1/LicenseService/1`
`Id: 1`
`Code:`
`Message:`
`...`

**Comment by sahanaramavana** [comment]
Hi @donzef ,

iLOlicense has been added with delete command for deletion of the license . This will be part of 3.6 and 4.0 versions of iLOrest .

Thanks & Regards,
iLORest Team

**Comment by donzef** [comment]
Thanks, I'll give it a try when available and close this issue accordingly.
