### ISSUE TITLE
Unable to flash ROM on DL360 Gen10

### ISSUE THREAD

**Issue by isvicbhasme** [HewlettPackard/python-redfish-utility#54]
On some DL360 Gen10 servers I am unable to flash the ROM firmware, also there are no errors being reported. The debug logs don't seem to give any clues. I need to perform the upgrade from an automation script and not from the UI.

```
root@localhost:/home/abc# sudo ilorest flashfwpkg /tmp/U32_2.34_04_08_2020.fwpkg --forceupload -u administrator -p $ILO_PASS
iLOrest : RESTful Interface Tool version 3.5.0.0
Copyright (c) 2014-2022 Hewlett Packard Enterprise Development LP
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Discovering data...Done
root@localhost:/home/abc# echo $?
0
```

The output of the same command with `--debug` option is attached as a file since its huge - [flashfwpkg_debug.txt](https://github.com/HewlettPackard/python-redfish-utility/files/8925805/flashfwpkg_debug.txt). Can someone point me in the right direction please.

**Comment by sahanaramavana** [comment]
Hi @isvicbhasme ,

Could you please check with our latest released version 3.5.1 , 

we tried it with the same and we are able to flash the FW without any exception. 

Also checked in your debug file you have attached i see 200 OK for all the actions and no error is captured. 

Would like to know whether the server did not get updated with the fwpkg file. 

Thanks & Regards,
iLORest Team

**Comment by isvicbhasme** [comment]
Hi @sahanaramavana,

For some historical reason we were copying an older version of ilorest_chif.so to `/usr/lib/x86_64-linux-gnu/ilorest_chif.so` thereby overwriting the ilorest_chif.so coming from the ilorest debian package. This obviously led to AttributeError due to certain missing symbols - `AttributeError: /usr/lib/x86_64-linux-gnu/ilorest_chif.so: undefined symbol: isFwpkg20`. After removing the ilorest_chif.so from our scripts we are able to flash the firmware successfully.

As part of `FwpkgCommand.py - run()` the AttributeError is not caught and gets lost in the finally block. One suggestion would be to capture all Exceptions & log them - https://github.com/HewlettPackard/python-redfish-utility/blob/master/src/extensions/iLO%20REPOSITORY%20COMMANDS/FwpkgCommand.py#L173

Thank you

**Comment by sahanaramavana** [comment]
Hi @isvicbhasme ,

We highly appreciate your valuable suggestion .  We shall definitely relook into this and take it as enhancement .

Thanks & Regards,
iLOrest Team
