### ISSUE TITLE
How to run (diagnostics)HVT using ipprofiles on Gen9/10 servers?

### ISSUE THREAD

**Issue by yyghzy** [HewlettPackard/python-redfish-utility#55]
Hi team, 
I don't know what should be written in the ipprofile json file for HVT. Can you provide a template file? 
Thanks.

**Comment by rajeevkallur** [comment]
Please check the documentation of ipprofiles at
https://hewlettpackard.github.io/python-redfish-utility/#ipprofiles-command

ipprofiles -D -f outpufile1
 
optional arguments:
  -h, --help            show this help message and exit
  -r, --running         Show status of the currently running or last job executed
  -D, --diags           Get result of last HVT (diagnostics) run as part of an ipprofile job
  -f FILENAME, --filename FILENAME
                        Write results to the specified file.
  --delete DEL_KEY      Look for the key or keys in the ipprofile manager and delete
  -s START_IP, --start START_IP
                        Copies the specified ip profile into the job queue and starts it
  -t SLEEP_TIME, --sleeptime SLEEP_TIME
                        Sleep time in seconds when server in OS mode and rebooted
