### ISSUE TITLE
Question - getting the display name from redfish's bios

### ISSUE THREAD

**Issue by erickyi2006** [HewlettPackard/python-redfish-utility#56]
From DELL, I can get the displayname of bios through their redfish API
Is there an equivalent for HP?

Current url I am using.
URL = https://{host}/redfish/v1/systems/1/bios/settings

**Comment by rajeevkallur** [comment]
Please use rawget command of ilorest tool.  As part of redfish standard, Name and Id will be displayed as below.
{
  "@odata.context": "/redfish/v1/$metadata#Bios.Bios",
  "@odata.etag": "W/\"2C1A347CA779C1C1C1E0568B50A87759\"",
  "@odata.id": "/redfish/v1/systems/1/bios/settings/",
  "@odata.type": "#Bios.v1_0_0.Bios",
  "AttributeRegistry": "BiosAttributeRegistryU32.v1_2_68",
  "Attributes": {
    "AcpiHpet": "Enabled",
    "AcpiRootBridgePxm": "Enabled",
    "AcpiSlit": "Enabled",
    "AdjSecPrefetch": "Enabled",
    "AdminEmail": "",
    "AdminName": "new_user",
    "AdminOtherInfo": "",
    "AdminPhone": "",
    "AdvCrashDumpMode": "Disabled",
    "AdvancedMemProtection": "FastFaultTolerantADDDC",
    "AsrStatus": "Enabled",
    "AsrTimeoutMinutes": "Timeout10",
    "AssetTagProtection": "Unlocked",
    "AutoPowerOn": "RestoreLastState",
    "BootMode": "Uefi",
    "BootOrderPolicy": "RetryIndefinitely",
    "ChannelInterleaving": "Enabled",
    "CollabPowerControl": "Enabled",
    "ConsistentDevNaming": "LomsAndSlots",
    "CustomPostMessage": "",
    "DaylightSavingsTime": "Disabled",
    "DcuIpPrefetcher": "Enabled",
    "DcuStreamPrefetcher": "Enabled",
    "Dhcpv4": "Enabled",
    "DynamicPowerCapping": "Disabled",
    "EmbNicEnable": "Auto",
    "EmbNicLinkSpeed": "Auto",
    "EmbNicPCIeOptionROM": "Enabled",
    "EmbSas1Aspm": "Disabled",
    "EmbSas1Boot": "TwentyFourTargets",
    "EmbSas1Enable": "Auto",
    "EmbSas1LinkSpeed": "Auto",
    "EmbSas1PcieOptionROM": "Enabled",
    "EmbSata1Aspm": "Disabled",
    "EmbSata2Aspm": "Disabled",
    "EmbVideoConnection": "Auto",
    "EmbeddedDiagnostics": "Enabled",
    "EmbeddedSata": "Ahci",
    "EmbeddedSerialPort": "Com2Irq3",
    "EmbeddedUefiShell": "Enabled",
    "EmsConsole": "Disabled",
    "EnabledCoresPerProc": 0,
    "EnergyEfficientTurbo": "Enabled",
    "EnergyPerfBias": "BalancedPerf",
    "EraseUserDefaults": "No",
    "ExtendedAmbientTemp": "Disabled",
    "ExtendedMemTest": "Disabled",
    "F11BootMenu": "Enabled",
    "FCScanPolicy": "CardConfig",
    "FanFailPolicy": "Shutdown",
    "FanInstallReq": "EnableMessaging",
    "FlexLom1Aspm": "Disabled",
    "HttpSupport": "Auto",
    "HwPrefetcher": "Enabled",
    "IODCConfiguration": "Auto",
    "IntelDmiLinkFreq": "Auto",
    "IntelNicDmaChannels": "Enabled",
    "IntelPerfMonitoring": "Disabled",
    "IntelProcVtd": "Enabled",
    "IntelTxt": "Disabled",
    "IntelligentProvisioning": "Enabled",
    "InternalSDCardSlot": "Enabled",
    "IpmiWatchdogTimerAction": "PowerCycle",
    "IpmiWatchdogTimerStatus": "IpmiWatchdogTimerOff",
    "IpmiWatchdogTimerTimeout": "Timeout30Min",
    "Ipv4Address": "0.0.0.0",
    "Ipv4Gateway": "0.0.0.0",
    "Ipv4PrimaryDNS": "0.0.0.0",
    "Ipv4SecondaryDNS": "0.0.0.0",
    "Ipv4SubnetMask": "0.0.0.0",
    "Ipv6Address": "::",
    "Ipv6ConfigPolicy": "Automatic",
    "Ipv6Duid": "Auto",
    "Ipv6Gateway": "::",
    "Ipv6PrimaryDNS": "::",
    "Ipv6SecondaryDNS": "::",
    "LLCDeadLineAllocation": "Enabled",
    "LlcPrefetch": "Disabled",
    "LocalRemoteThreshold": "Auto",
    "MaxMemBusFreqMHz": "Auto",
    "MaxPcieSpeed": "PerPortCtrl",
    "MemClearWarmReset": "Disabled",
    "MemFastTraining": "Enabled",
    "MemMirrorMode": "Full",
    "MemPatrolScrubbing": "Enabled",
    "MemRefreshRate": "Refreshx1",
    "MemoryControllerInterleaving": "Auto",
    "MemoryRemap": "NoAction",
    "MinProcIdlePkgState": "C6Retention",
    "MinProcIdlePower": "C6",
    "MixedPowerSupplyReporting": "Enabled",
    "NetworkBootRetry": "Enabled",
    "NetworkBootRetryCount": 20,
    "NicBoot1": "NetworkBoot",
    "NicBoot2": "Disabled",
    "NicBoot3": "Disabled",
    "NicBoot4": "Disabled",
    "NodeInterleaving": "Disabled",
    "NumaGroupSizeOpt": "Flat",
    "NvmeOptionRom": "Enabled",
    "OpportunisticSelfRefresh": "Disabled",
    "PciPeerToPeerSerialization": "Disabled",
    "PciResourcePadding": "Normal",
    "PciSlot1Aspm": "Disabled",
    "PciSlot1Bifurcation": "Auto",
    "PciSlot1Enable": "Auto",
    "PciSlot1LinkSpeed": "Auto",
    "PciSlot1OptionROM": "Enabled",
    "PciSlot2Bifurcation": "Auto",
    "PersistentMemBackupPowerPolicy": "WaitForBackupPower",
    "PlatformCertificate": "Enabled",
    "PostBootProgress": "Disabled",
    "PostDiscoveryMode": "Auto",
    "PostF1Prompt": "Delayed20Sec",
    "PostVideoSupport": "DisplayAll",
    "PostedInterruptThrottle": "Enabled",
    "PowerButton": "Enabled",
    "PowerOnDelay": "Random",
    "PowerRegulator": "OsControl",
    "PreBootNetwork": "Auto",
    "PrebootNetworkEnvPolicy": "Auto",
    "PrebootNetworkProxy": "",
    "ProcAes": "Enabled",
    "ProcHyperthreading": "Enabled",
    "ProcTurbo": "Enabled",
    "ProcVirtualization": "Enabled",
    "ProcX2Apic": "Enabled",
    "ProcessorConfigTDPLevel": "Normal",
    "ProcessorJitterControl": "Disabled",
    "ProcessorJitterControlFrequency": 0,
    "ProcessorJitterControlOptimization": "ZeroLatency",
    "ProductId": "867959-B22",
    "RedundantPowerSupply": "BalancedMode",
    "RefreshWatermarks": "Auto",
    "RemovableFlashBootSeq": "ExternalKeysFirst",
    "RestoreDefaults": "No",
    "RestoreManufacturingDefaults": "No",
    "RomSelection": "CurrentRom",
    "SataSecureErase": "Disabled",
    "SaveUserDefaults": "No",
    "SecStartBackupImage": "Disabled",
    "SecureBootStatus": "Disabled",
    "SerialConsoleBaudRate": "BaudRate115200",
    "SerialConsoleEmulation": "Vt100Plus",
    "SerialConsolePort": "Auto",
    "SerialNumber": "SGH849SCKG",
    "ServerAssetTag": "abcd1",
    "ServerConfigLockStatus": "Disabled",
    "ServerName": "localhost",
    "ServerOtherInfo": "",
    "ServerPrimaryOs": "",
    "ServiceEmail": "",
    "ServiceName": "",
    "ServiceOtherInfo": "",
    "ServicePhone": "",
    "SetupBrowserSelection": "Auto",
    "Slot1MctpBroadcastSupport": "Enabled",
    "Slot1NicBoot1": "NetworkBoot",
    "Slot1NicBoot2": "Disabled",
    "Slot2MctpBroadcastSupport": "Enabled",
    "Sriov": "Enabled",
    "StaleAtoS": "Disabled",
    "SubNumaClustering": "Disabled",
    "ThermalConfig": "OptimalCooling",
    "ThermalShutdown": "Enabled",
    "TimeFormat": "Utc",
    "TimeZone": "UtcP530",
    "TpmChipId": "StMicroGen10",
    "TpmFips": "NonFipsMode",
    "TpmFipsModeSwitch": "NoAction",
    "TpmModeSwitchOperation": "NoAction",
    "TpmOperation": "NoAction",
    "TpmState": "PresentEnabled",
    "TpmType": "Tpm12",
    "TpmUefiOpromMeasuring": "Disabled",
    "TpmVisibility": "Visible",
    "UefiOptimizedBoot": "Disabled",
    "UefiSerialDebugLevel": "Disabled",
    "UefiShellBootOrder": "Disabled",
    "UefiShellScriptVerification": "Disabled",
    "UefiShellStartup": "Disabled",
    "UefiShellStartupLocation": "Auto",
    "UefiShellStartupUrl": "",
    "UefiShellStartupUrlFromDhcp": "Disabled",
    "UefiVariableAccessFwControl": "Disabled",
    "UncoreFreqScaling": "Auto",
    "UrlBootFile": "",
    "UrlBootFile2": "",
    "UrlBootFile3": "",
    "UrlBootFile4": "",
    "UsbBoot": "Enabled",
    "UsbControl": "UsbEnabled",
    "UserDefaultsState": "Disabled",
    "UtilityLang": "English",
    "VirtualInstallDisk": "Disabled",
    "VirtualSerialPort": "Com1Irq4",
    "VlanControl": "Disabled",
    "VlanId": 0,
    "VlanPriority": 0,
    "WakeOnLan": "Enabled",
    "WorkloadProfile": "GeneralPowerEfficientCompute",
    "XptPrefetcher": "Auto",
    "iSCSIPolicy": "SoftwareInitiator"
  },
  "Id": "settings",
  "Name": "BIOS Pending Settings"
}
