### ISSUE TITLE
set IPv4StaticAddresses 

### ISSUE THREAD

**Issue by ralfgro** [HewlettPackard/python-redfish-utility#60]
I found this issue https://github.com/HewlettPackard/python-redfish-utility/issues/32 but the answer there does not help me to set a static address.

I'm also struggling with setting a static IP to an ILO. Can someone please show a working example? I failed to find one. There are some examples but none that really has all steps in a real world env.

How should I use the example above with HPEs ilorest tool? Why is it so hard to set a static ILO IP with this tool? No working example anywhere.

`IPv4StaticAddresses=f"[{{ {ad}, {nm}, {gtw} }}]" if pyhton 3
`
```
select EthernetInterface.v1_4_1
get IPv4Addresses --filter "@odata.id=/redfish/v1/Managers/1/EthernetInterfaces/1/"

IPv4StaticAddresses=
                     SubnetMask=255.255.255.0
                     Gateway=172.17.21.1
                     Address=172.17.21.34

 set IPv4StaticAddresses=172.17.21.34 --filter "@odata.id=/redfish/v1/Managers/1/EthernetInterfaces/1/"
'172.17.21.34' is not a valid setting for 'IPv4StaticAddresses', expecting an array

'172.17.21.34' is not a valid setting for 'IPv4StaticAddresses'




set IPv4StaticAddresses=f"[{{ {172.17.21.34}, {255.255.255.0}, {172.17.21.1} }}] --filter "@odata.id=/redfish/v1/Managers/1/EthernetInterfaces/1/"
'f"[{{' is not a valid setting for 'IPv4StaticAddresses', expecting an array

'f"[{{' is not a valid setting for 'IPv4StaticAddresses'
```

**Comment by donzef** [comment]
Perso, I use a `rawpatch` command with the following:

* Identify the dedicated network interface URI:
`ilorest get --json "@odata.id"   --filter Name="Manager Dedicated Network Interface"`

* Perform `rawpatch` on the resulting URI:
`ilorest  rawpatch SetDedicatedEthernetInterface.json` 

with the following content:

```
{
    "/redfish/v1/Managers/1/EthernetInterfaces/1/": {
        "DHCPv4": {
            "DHCPEnabled": false,
            "UseDNSServers": false,
            "UseDomainName": false,
            "UseGateway": false,
            "UseNTPServers": false,
            "UseStaticRoutes": false
        },
        "IPv4Addresses": [{
            "Address": "172.228.75.2",
            "Gateway": "172.228.72.1",
            "SubnetMask": "255.255.252.0"
        }]
    }
}
```

* Reset the iLO: `ilorest iloreset`

**Comment by ralfgro** [comment]
Thanks for the hint, but its not working for me.


iLOrest > rawpatch /tmp/SetDedicatedEthernetInterface.json
The property "AddressOrigin" is a read-only property and cannot be assigned a value, or not valid for this resource.


```
{
    "/redfish/v1/Managers/1/EthernetInterfaces/1/": {
        "DHCPv4": {
            "DHCPEnabled": false,
            "UseDNSServers": false,
            "UseDomainName": false,
            "UseGateway": false,
            "UseNTPServers": false,
            "UseStaticRoutes": false
       },
       "IPv4Addresses": [{
           "Address": "172.17.21.34",
           "AddressOrigin": "Static",
           "Gateway": "172.17.21.1",
           "SubnetMask": "255.255.255.0"
       }]
    }
}
```

**Comment by donzef** [comment]
While it would be a good idea to update to the latest iLOrest version, I've forgotten to specify the selection of the EthernetInterface type in the command retrieving the URI of the dedicated manager interface:

`ilorest get --json "@odata.id" --filter Name="Manager Dedicated Network Interface" --select EthernetInterface.` 

My bad. Sorry.

**Comment by rajeevkallur** [comment]
{
  "@odata.id": "/redfish/v1/Managers/1/EthernetInterfaces/1/"
}
