### ISSUE TITLE
Unable to use REDFISH-utility on MAC

### ISSUE THREAD

**Issue by mnh2005124** [HewlettPackard/python-redfish-utility#61]
<img width="623" alt="Screenshot 2022-10-10 at 10 37 21 AM" src="https://user-images.githubusercontent.com/30888012/194792266-b78bed85-bd20-41c0-8cef-da5682103539.png">
<img width="530" alt="Screenshot 2022-10-10 at 10 37 37 AM" src="https://user-images.githubusercontent.com/30888012/194792291-075d93bd-9ad3-4ca2-8986-1bc2aae82b57.png">

**Comment by rajeevkallur** [comment]
@mnh2005124 ,Please check the diskspace available and other permissions.  I am able to successfully install on my mac

![image](https://user-images.githubusercontent.com/21117913/194798322-f5c3b5ed-cdb0-4920-9c50-e4d7ef4cf48d.png)

**Comment by mnh2005124** [comment]
I tried all but failed , which package and how you installed it , Could you please share the details 
![Uploading Screenshot 2022-10-10 at 1.08.43 PM.png…]()

**Comment by mnh2005124** [comment]
Sir, you have tested the package on M1, I am using intel for the same. I believe  they are different

**Comment by rajeevkallur** [comment]
here the architecture is arm64
![image](https://user-images.githubusercontent.com/21117913/194808202-c6981659-bee3-4591-895e-198d023655b0.png)

**Comment by rajeevkallur** [comment]
can u send the same from your system?

**Comment by mnh2005124** [comment]
manishkumar@Manish-MAC Downloads % uname -a
Darwin Manish-MAC.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64
manishkumar@Manish-MAC Downloads %

**Comment by rajeevkallur** [comment]
As you see, it is x86_64 architecture.  Is this officially supported by Apple/MAC OS?

**Comment by mnh2005124** [comment]
Yes it is , its previous generation. As of now everything M1 or M2 but intel based also supported

**Comment by rajeevkallur** [comment]
Please come thru' proper channel via support/pointnext team. We need to take it as a new feature request as it needs to recompiled/repackaged on x86 mac system.

**Comment by mnh2005124** [comment]
Thanks for the help Rajeev
