### ISSUE TITLE
ilorest 3.6.0 serverinfo json schema change

### ISSUE THREAD

**Issue by petgalko** [HewlettPackard/python-redfish-utility#66]
With older ilorest releases (e.g. 3.1.1) the json output from `/usr/sbin/ilorest --nologo serverinfo --memory --fans --processors --thermals --power -j` was just single json. With ilorest 3.5.0 there are 2 concatenated outputs in json (first json with general power info and second with same data and json (redfish) schema as older release.
e.g. for power supplies the 'State' and 'Health' were in section 'Status' for each power supply (same like redfish).
With ilorest 3.6.0 there are 5 concatenated json in completely different json schema. 
e.g. for power supplies the 'State' and 'Health' are directly in each 'Power Supply X' (where X is the nr of power supply) - without the 'Status' section (also path to 'Power Supply X' is different).
Is this bug in ilorest 3.6.0, or there is some new json schema, which would be used also in future release?

**Comment by rajeevkallur** [comment]
@petgalko , Please provide us the debug logs with ilorest -v -d option.

**Comment by petgalko** [comment]
@rajeevkallur thanks for response.
The logs are attached in: 
[ilorest_logs.tar.gz](https://github.com/HewlettPackard/python-redfish-utility/files/10254638/ilorest_logs.tar.gz)
For each version there is iLOrest.log (renamed to iLOrest.log-3.1.1 or iLOrest.log-3.6.0) + scripts output from console.
Server serial number replaced to CZ123456AB; hostname is dlserver.

**Comment by rajeevkallur** [comment]
Fixed in latest version of ilorest.  Please wait for 4.1 version.

**Comment by rajeevkallur** [comment]
**Fixed:**
{
  "fans": {
    "Fan 3": {
      "Health": "OK",
      "Hot Pluggable": true,
      "Location": "System",
      "Reading": "60%",
      "Redundant": true,
      "State": "Enabled"
    },
    "Fan 4": {
      "Health": "OK",
      "Hot Pluggable": true,
      "Location": "System",
      "Reading": "60%",
      "Redundant": true,
      "State": "Enabled"
    },
    "Fan 5": {
      "Health": "OK",
      "Hot Pluggable": true,
      "Location": "System",
      "Reading": "60%",
      "Redundant": true,
      "State": "Enabled"
    },
    "Fan 6": {
      "Health": "OK",
      "Hot Pluggable": true,
      "Location": "System",
      "Reading": "60%",
      "Redundant": true,
      "State": "Enabled"
    },
    "Fan 7": {
      "Health": "OK",
      "Hot Pluggable": true,
      "Location": "System",
      "Reading": "60%",
      "Redundant": true,
      "State": "Enabled"
    }
  },
  "memory": {
    "Memory/DIMM Board Information": {
      "Advanced Memory Protection Status: A3DC": {
        "Board CPU: 1": {
          "Board Memory Frequency": "2400 MHz",
          "Board Memory Voltage": "1200 MiB",
          "Total Memory Size": "16384 MiB"
        },
        "Board CPU: 2": {
          "Board Memory Frequency": "2400 MHz",
          "Board Memory Voltage": "1200 MiB",
          "Total Memory Size": "0 MiB"
        }
      }
    },
    "Memory/DIMM Configuration 1": {
      "Capacity": "16384 MiB",
      "Health": "OK",
      "Location": "PROC 1 DIMM 8",
      "Memory Type": "DRAM DDR4",
      "Speed": "2400 MHz",
      "Status": "GoodInUse"
    }
  },
  "power": {
    "Power Metrics on 20 min. Intervals": {
      "Average Power": "96 W",
      "Max Consumed Power": "102 W",
      "Minimum Consumed Power": "96 W"
    },
    "Power Supply 1": {
      "Health": "OK",
      "Hotplug Capable": true,
      "Input Voltage": "229 V",
      "Input Voltage Type": "ACHighLine",
      "Last Power Output": "97 W",
      "Power Capacity": "800 W",
      "State": "Enabled",
      "iPDU Capable": false
    },
    "Total Power Capacity": "800 W",
    "Total Power Consumed": "97 W"
  },
  "processor": {
    "Processor 1": {
      "Cores": 8,
      "Health": "OK",
      "L1-Cache": "512 KB",
      "L2-Cache": "8192 KB",
      "L3-Cache": "11264 KB",
      "Max Speed": "4000 MHz",
      "Model": "Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz",
      "Socket": "Proc 1",
      "Speed": "2100 MHz",
      "Step": "4",
      "Threads": 16
    }
  },
  "thermals": {
    "Sensor #12:": {
      "Critical Threshold": "60 C",
      "Current Temp": "35 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #14:": {
      "Critical Threshold": "60 C",
      "Current Temp": "27 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #15:": {
      "Critical Threshold": "60 C",
      "Current Temp": "25 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "Intake"
    },
    "Sensor #16:": {
      "Critical Threshold": "115 C",
      "Current Temp": "32 C",
      "Fatal Threshold": "120 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #18:": {
      "Critical Threshold": "115 C",
      "Current Temp": "30 C",
      "Fatal Threshold": "120 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #19:": {
      "Critical Threshold": "115 C",
      "Current Temp": "29 C",
      "Fatal Threshold": "120 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #1:": {
      "Critical Threshold": "42 C",
      "Current Temp": "27 C",
      "Fatal Threshold": "47 C",
      "Health": "OK",
      "Location": "Intake"
    },
    "Sensor #22:": {
      "Critical Threshold": "100 C",
      "Current Temp": "34 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #23:": {
      "Critical Threshold": "110 C",
      "Current Temp": "65 C",
      "Fatal Threshold": "115 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #24:": {
      "Critical Threshold": "90 C",
      "Current Temp": "35 C",
      "Fatal Threshold": "95 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #25:": {
      "Critical Threshold": "100 C",
      "Current Temp": "50 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #26:": {
      "Critical Threshold": "85 C",
      "Current Temp": "29 C",
      "Fatal Threshold": "90 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #28:": {
      "Critical Threshold": "90 C",
      "Current Temp": "30 C",
      "Fatal Threshold": "95 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #29:": {
      "Critical Threshold": "90 C",
      "Current Temp": "32 C",
      "Fatal Threshold": "95 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #2:": {
      "Critical Threshold": "70 C",
      "Current Temp": "40 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "CPU"
    },
    "Sensor #31:": {
      "Critical Threshold": "90 C",
      "Current Temp": "31 C",
      "Fatal Threshold": "95 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #35:": {
      "Critical Threshold": "75 C",
      "Current Temp": "29 C",
      "Fatal Threshold": "80 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #36:": {
      "Critical Threshold": "None C",
      "Current Temp": "24 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "PowerSupply"
    },
    "Sensor #38:": {
      "Critical Threshold": "None C",
      "Current Temp": "40 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "PowerSupply"
    },
    "Sensor #40:": {
      "Critical Threshold": "100 C",
      "Current Temp": "22 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "PowerSupply"
    },
    "Sensor #41:": {
      "Critical Threshold": "75 C",
      "Current Temp": "26 C",
      "Fatal Threshold": "80 C",
      "Health": "OK",
      "Location": "PowerSupply"
    },
    "Sensor #42:": {
      "Critical Threshold": "None C",
      "Current Temp": "30 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "CPU"
    },
    "Sensor #51:": {
      "Critical Threshold": "110 C",
      "Current Temp": "53 C",
      "Fatal Threshold": "115 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #52:": {
      "Critical Threshold": "105 C",
      "Current Temp": "46 C",
      "Fatal Threshold": "110 C",
      "Health": "OK",
      "Location": "SystemBoard"
    },
    "Sensor #6:": {
      "Critical Threshold": "90 C",
      "Current Temp": "29 C",
      "Fatal Threshold": "None C",
      "Health": "OK",
      "Location": "Memory"
    }
  }
}
