### ISSUE TITLE
syntax errors in Set_Federation_Multicast_Options.sh (and probably other scripts)

### ISSUE THREAD

**Issue by ralfgro** [HewlettPackard/python-redfish-utility#67]
* ilorest set Oem/Hpe/FederationConfig/iLOFederationManagerment=Enabled
--> iLOFederationManagerment should be iLOFederationManagement

* ilorest set Oem/Hpe/FederationConfig/MulticastDiscoveryEnabled=Enabled
--> MulticastDiscoveryEnabled does not exist it should be MulticastDiscovery=Enabled

The longer I work with ilorest and api, I get more and more the feeling that most of the stuff was never tested...

**Comment by rajeevkallur** [comment]
Fixed
