### ISSUE TITLE
ilorest virtualmedia works but show error weirdly

### ISSUE THREAD

**Issue by efex2000** [HewlettPackard/python-redfish-utility#68]
.\ilorest.exe login 10.10.10.15 -u admin -p abcd+1234
.\ilorest.exe virtualmedia 2 http://10.10.10.145/isos/gen10spp.iso

.\ilorest.exe : The operation completed successfully.
At line:2 char:1
+ .\ilorest.exe virtualmedia 2 http://10.51.28.145/isos/gen10spp.iso
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The operation completed successfully.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by rajeevkallur** [comment]
Please provide the debug logs by running with ilorest -d -v virtualmedia 2 http://10.10.10.145/isos/gen10spp.iso

**Comment by rajeevkallur** [comment]
Not able to reproduce this with latest version of ilorest tool.  Closing this case
