### ISSUE TITLE
ilorest v4.0.0.0 connect times out on flashfwpkg push

### ISSUE THREAD

**Issue by pandatracs** [HewlettPackard/python-redfish-utility#69]
ilorest v4.0.0.0 flashfwpkg connection times out when pushing a fwpkg to a destination across a wan.  

ilorest v3.6.0.0 does not experience this problem when pushing the identical fwpkg from the same source to the same destination.

--------------------------
ilorest v4.0.0.0 Example:
--------------------------

C:\>ilorest flashfwpkg U32_2.68_07_14_2022.fwpkg --update_srs --url *** -u *** -p ***
iLOrest : RESTful Interface Tool version 4.0.0.0
Copyright (c) 2014-2022 Hewlett Packard Enterprise Development LP
--------------------------------------------------------------------------------
Discovering data...Done
Uploading firmware: U32_2.68_07_14_2022.signed.flash
Successfully checked 'U32_2.68_07_14_2022.signed.flash'.
Uploading component U32_2.68_07_14_2022.signed.flash.
ERROR: ('Connection aborted.', timeout('The write operation timed out'))

--------------------------
ilorest v3.6.0.0 Example:
--------------------------

C:\>ilorest flashfwpkg U32_2.68_07_14_2022.fwpkg --update_srs --url *** -u *** -p ***
iLOrest : RESTful Interface Tool version 3.6.0.0
Copyright (c) 2014-2022 Hewlett Packard Enterprise Development LP
--------------------------------------------------------------------------------
Discovering data...Done
Uploading firmware: U32_2.68_07_14_2022.signed.flash
Successfully checked 'U32_2.68_07_14_2022.signed.flash'.
Uploading component U32_2.68_07_14_2022.signed.flash.
The operation completed successfully.
Component U32_2.68_07_14_2022.signed.flash uploaded successfully.
Waiting for iLO UpdateService to finish processing the component
00 hour(s) 03 minute(s) 10 second(s)
Firmware has successfully been flashed and a reboot is required for this firmware to take effect.

**Comment by donzef** [comment]
Experienced the same problem with ilO 5 firmware 2.78.

**Comment by rajeevkallur** [comment]
Looking into it

**Comment by rajeevkallur** [comment]
![image](https://user-images.githubusercontent.com/21117913/214552325-d675c7fa-d8f6-4260-a707-26a55d27c1d7.png)

**Comment by rajeevkallur** [comment]
was able to upload and flash successfully.  Please feel free to reopen if you find it with some platforms.

**Comment by pandatracs** [comment]
@rajeevkallur  Was your testing restricted to local uploads?  ilorest v4.0.0.0 works fine when uploading/flashing to systems located across nearby networks.  It only fails when uploading to distant systems.  This issue does not exist with ilo v3.6.0.0.

I work for a data center company.  We have HPE systems distributed across the US, Canada, Europe and Asia.  We have VPN interconnects between data centers for such management.  Using ilorest v3.6.0.0 I can upload the firmware from a distribution point based in the US to all of our other data centers without issue.  However with ilorest v4.0.0.0 this fails with the errors I originally posted.  ilorest v4.0.0.0 seems to be sensitive to latency; whereas, v3.6.0.0 was not.

Unless you're testing the upload/flash across long distances, its unlikely you'll see the error.

**Comment by rajeevkallur** [comment]
ok, we will check this

**Comment by rajeevkallur** [comment]
This will be fixed in the upcoming release of ilorest 4.1
