### ISSUE TITLE
Feature for ilorest createlogicaldrive quickdrive to include all options

### ISSUE THREAD

**Issue by tkakkonen** [HewlettPackard/python-redfish-utility#7]
Hi,

Seems that customdrive has many of the raid options implemented but quickdrive option does not use these. Could these be added also to quickdrive or are they somehow specific for customdrive creation?
Im trying to create raid and would like to use quickdrive to select drives but also set options like size and accelerator iex ansible call.
ilorest createlogicaldrive quickdrive {{hostvars[item]['DriveParameters']}} --accelerator-type=ControllerCache

**Comment by Yergidy** [comment]
We should be able to add an option for minimum size in GiB. I will have to contact the smart array team to see what else is possible and what isn't.

**Comment by Yergidy** [comment]
We have added the minimum size in GiB option in the latest release. Unfortunately the rest of the options are specific to custom drive creation.

**Comment by rajeevkallur** [comment]
![image](https://user-images.githubusercontent.com/21117913/98096425-c0f10e00-1eb1-11eb-9a6e-ba1f96e5e946.png)
