### ISSUE TITLE
Serverclone command doesn't check wheather server is up or not. 

### ISSUE THREAD

**Issue by akhrnkn** [HewlettPackard/python-redfish-utility#72]
ilorest v4.0.0.0 "serverclone load" asks "The system is ready to be reset. Perform a reset now?"  in line 464 of ServerCloneCommand.py .
When I answer y, it runs "ilorest reboot" with coldboot option in line 481.
 
It seems the program assumes the system is up.
But the system may be stopped. No document says it is required to be up when executing "serverclone load".
 
So when aswer y with the system stopped, the program aborted with message "iLO.2.15.InvalidOperationForSystemState".
I think code for check system state before asking reset or not.

**Comment by rajeevkallur** [comment]
@akhrnkn ,  Please recheck with latest version of ilorest 4.6.0.0

**Comment by rajkumar14** [comment]
@akhrnkn This is fixed in build 5.0.0.0. Please you can verify.
