### ISSUE TITLE
Admin remote Cache Problem

### ISSUE THREAD

**Issue by Justice81** [HewlettPackard/python-redfish-utility#74]
If using as non admin under linux debian its not working correctly

(www-data because i wnat to use the tool within a monitoring system)

sudo -u www-data ilorest iloreset https://IP user password! -vv
iLOrest : RESTful Interface Tool version 4.0.0.0
Copyright (c) 2014-2022 Hewlett Packard Enterprise Development LP
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Local login initiated...

Both remote and local mode is accessible when RESTful Interface Tool is run as administrator. Only remote mode is available for non-admin user groups.
ILOREST return code: 5

And using nocache it is not working correctly:

as you can see if using ne nocache , ilorest ist connecting local not remote
ilorest iloreset https://ip user password -vv --nocache
iLOrest : RESTful Interface Tool version 4.0.0.0
Copyright (c) 2014-2022 Hewlett Packard Enterprise Development LP
---------------------------------------------------------------------------------------------------------------------------------------------------------------
Local login initiated...
Discovering data...Done
Monolith build process time: 1.761587142944336
A management processor reset is in progress.
ILOREST return code: 0

**Comment by rajeevkallur** [comment]
@Justice81 , Syntax is not correct.  Correct syntax is 

ilorest iloreset --url https://ip/ -u user -p password -vv --nocache

**Comment by rajeevkallur** [comment]
@Justice81 , Please test with latest ilorest version and let us know.
