### ISSUE TITLE
Enhancement: Provide a --silent optional arg to commands with a JSON output

### ISSUE THREAD

**Issue by donzef** [HewlettPackard/python-redfish-utility#75]
Some commands like the  `rawget` command write on stdin some messages (i.e. `The command completed successfully` ). Those kind of messages corrupt the  JSON output that cannot be parsed by programs like `jq` .

![image](https://user-images.githubusercontent.com/42031605/231787848-569719ef-9fd0-432d-954f-30e7677a37be.png)

**Comment by rajeevkallur** [comment]
Fixed!  Please use it as below.
ilorest --nologo rawget /redfish/v1/managers/1 --silent
