### ISSUE TITLE
ILORest 4.1.0.0 errors when attempting to flashfwpkg on iLO5

### ISSUE THREAD

**Issue by Mikey60606** [HewlettPackard/python-redfish-utility#77]
I am attempting to flash the BIOS on a Synergy 480 Gen10 and can successfully upload the fwpkg to the iLO respository. However when I attempt to flash I get the error below. I am new to using the ilorest util so perhaps I am missing a step or two prior to flashing? The fwpkg is valid as I am able to install it manually from the iLO repository.

C:\>ilorest flashfwpkg I42_2.80_04_20_2023.fwpkg --verbose --update_srs --url https://***.com -u *** -p ***
iLOrest : RESTful Interface Tool version 4.1.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
--------------------------------------------------------------------------------
Discovering data...Done
Uploading firmware: I42_2.80_04_20_2023.signed.flash
Successfully checked 'I42_2.80_04_20_2023.signed.flash'.
UpdateService state = COMPLETE
Uploading component I42_2.80_04_20_2023.signed.flash.
[400] No error message returned or unable to parse error response.
An invalid response body was returned: Expecting value: line 1 column 1 (char 0)An invalid response body was returned: Expecting value: line 1 column 1 (char 0)ERROR: 'NoneType' object is not subscriptable
ILOREST return code: 255

**Comment by rajeevkallur** [comment]
Fixed
