### ISSUE TITLE
ilorest rpms not signed correctly

### ISSUE THREAD

**Issue by mdidomenico4** [HewlettPackard/python-redfish-utility#80]
# rpm -Kv --nosignature ilorest-4.2.0.0-20.x86_64.rpm
ilorest-4.2.0.0-20.x86_64.rpm:
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    MD5 digest: NOTFOUND

as a recourse when i try to dnf install the rpm i get

Transaction test error: package ilorest-4.2.0.0-20.x86_64 does not verify: no digest

**Comment by rajeevkallur** [comment]
Fixed

**Comment by mdidomenico4** [comment]
which version will this fix get pulled into?
