### ISSUE TITLE
issue -p

### ISSUE THREAD

**Issue by manderson92** [HewlettPackard/python-redfish-utility#81]
hello. 

getting to to know ilorest
entered this command to get system information
get select --Bios --url DL32513ILO -u student -p #HPE2learn
(this is for a class and the iLO is on a closed network)
The error I get is: error argument -p/--password expected one argument
Any insight?

**Comment by rajeevkallur** [comment]
@manderson92 ,  Could you please enclose the password in quotes?  Also, try escaping the # special character like "\#HPE2learn"

**Comment by rajeevkallur** [comment]
Please feel free to reopen if you still have issue.
