### ISSUE TITLE
staged firmware info

### ISSUE THREAD

**Issue by mdidomenico4** [HewlettPackard/python-redfish-utility#83]
is there a way to see if firmware is staged for installation at next reboot?  i use the flashfwpkg command to flash a new bios on the server, which works fine and will install during the next reboot.  however, i would like some programmatic way of telling whether a new bios is staged in ilo and whether it will be installed at next reboot

**Comment by rajeevkallur** [comment]
@mdidomenico4 , You can probably use taskqueue command which lists the pending tasks like installation at next reboot.

**Comment by rajeevkallur** [comment]
After BIOS flash, there is a message to reboot the server.  This is as expected.  Rebooting the server will enable the new BIOS.
