### ISSUE TITLE
Volume Creation fails "Unable to locate instance for volume"

### ISSUE THREAD

**Issue by alexbarta** [HewlettPackard/python-redfish-utility#84]
Hello,

Currently I'm using a DL380 Gen11 w/ iLO 6 v1.30.
I've been trying to figure out what's the right syntax for volume creation, from docs is not clear how to specify physical drive location or drive indices:
```
createvolume volume Raid1 Slot=14:Port=2:Box=3:Bay=4,Slot=14:Port=2:Box=3:Bay=8 --DisplayName test --storageid=DE00C000 --controller=0
```
results in "Unable to locate instance for volume." error . Actually whatever you put in the "Drive_Indices" option argument results in the same error.

**Comment by rajeevkallur** [comment]
Please use as below and let us know

createvolume volume Raid1 2:3:4,2:3:8 --DisplayName test --storageid=DE00C000 --controller=0

**Comment by rajeevkallur** [comment]
Fixed
