### ISSUE TITLE
Support for SOCKS5 proxy

### ISSUE THREAD

**Issue by gadamiak** [HewlettPackard/python-redfish-utility#9]
Does the `ilorest` client support connecting via SOCKS5 proxy?

I want to connect to remote systems which I can access via an SSH gateway. Exporting `https_proxy` does work with curl, but not with `ilorest`:

```bash
$ export https_proxy=socks5://localhost:8012/
$ curl https://192.168.100.29/redfish/v1/ -Lk -u user:pass
# JSON output
$ ilorest login https://192.168.100.29 -u user -p pass
iLOrest : RESTful Interface Tool version 2.3
Copyright (c) 2014, 2018 Hewlett Packard Enterprise Development LP
...
Error: Could not reach URL. Retries have been exhausted.
```

I would expect the client to support proxy as curl (and other CLI utilities) do.

**Comment by Yergidy** [comment]
@gadamiak While it currently does not we will look into adding support for the SOCKS5 proxy.

**Comment by gadamiak** [comment]
Thanks! That will be very helpful.

**Comment by dirkvdplas** [comment]
+1 
support for HTTP_PROXY would also be a nice improvement!

**Comment by Yergidy** [comment]
Version 2.5 adds support for SOCKS and HTTP proxies.
