### ISSUE TITLE
Flashing v1 FWPKGs without PLDMImage still results in KeyError

### ISSUE THREAD

**Issue by larsux** [HewlettPackard/python-redfish-utility#90]
Hi @rajeevkallur,
I just test the new Version 4.5.0.0, but it looks like the issue from #82 still exists:

```
# ilorest -v flashfwpkg ilo5_210.fwpkg
iLORest : RESTful Interface Tool version 4.5.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
-------
Local login initiated...
Discovering data...Done
ERROR: 'PLDMImage'
iLORest return code: 255
```

The erroneous line in the code seems untouched:
https://github.com/HewlettPackard/python-redfish-utility/blob/33e5056cccfbcb0cad5ba18c0d6781cb75cea09b/src/extensions/iLO_REPOSITORY_COMMANDS/FwpkgCommand.py#L315

**Comment by moonrail** [comment]
Still present in 4.6.0.0

**Comment by rajeevkallur** [comment]
Will be fixed soon.  Please recheck in latest build.

**Comment by larsux** [comment]
Error still exists in latest build ([ilorest-4.7.0.0-24.x86_64.rpm](https://github.com/HewlettPackard/python-redfish-utility/releases/download/v4.7.0.0/ilorest-4.7.0.0-24.x86_64.rpm)):
```
$ sudo ilorest -v flashfwpkg ilo5_210.fwpkg 
iLORest : RESTful Interface Tool version 4.7.0.0
Copyright (c) 2014-2023 Hewlett Packard Enterprise Development LP
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Local login initiated...
Discovering data...Done
ERROR: 'PLDMImage'
iLORest return code: 255
```

**Comment by larsux** [comment]
Bug is fixed in latest version 4.8.0.0

**Comment by rajeevkallur** [comment]
Closing.

**Comment by rajeevkallur** [comment]
Closed
