### ISSUE TITLE
Cancel Pending BiosDefaults change?

### ISSUE THREAD

**Issue by Galantry** [HewlettPackard/python-redfish-utility#93]
Hi, I'm new here. I spoke with a support agent via chat who recommended I come here.

I'm new to iLO and have been asked to look at a ProLiant server that someone else configured. I wanted to try to find if iLO had been configured, had an IP, and made the stupid mistake of running biosdefaults thinking it would output the current defaults, not reset the BIOS to factory. 

It's currently pending, is there a way to cancel that change?

The agent in chat suggested I run:
biosdefaults --userdefaults 
And that it would override the pending reset and maintain the current saved settings, but he couldn't confirm, and so asked me to ask here.

Can anyone assist?

Thanks.

**Comment by rajkumar14** [comment]
@Galantry As suggested chat agent its valid command, Please try below commands
ilorest biosdefaults --userdefaults
ilorest reboot ForceRestart
for more information please refer below document:
https://servermanagementportal.ext.hpe.com/docs/redfishservices/ilos/supplementdocuments/biosdoc/#iLOrest

**Comment by rajeevkallur** [comment]
internal JIRA filed
