### ISSUE TITLE
4.7.0.0 and 4.8.0.0 ERROR: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by QFiaux** [HewlettPackard/python-redfish-utility#95]
Hi,

ilorest 4.6.0.0 is working as expected (see output below) and should be used as a workaround:
Ilorest > ethernet --url 10.182.21.189 -u Administrator -p Password --network_ipv4 10.182.21.190,10.182.23.254,255.255.252.0
Discovering data...Done
The operation completed successfully.

Ilorest> iloreset --url 10.182.21.189 -u Administrator -p Password
Discovering data...Done
A management processor reset is in progress.

The IP is successfully changed to the desired one - 10.182.21.190.

4.7.0.0 and 4.8.0.0 returns the following error:

Ilorest > ethernet --url 10.182.21.189 -u Administrator -p Password --network_ipv4 10.182.21.190,10.182.23.254,255.255.252.0
Discovering data...Done
ERROR: 'str' object has no attribute 'items'

Thanks

**Comment by rajkumar14** [comment]
This is in our upcoming release build 4.9.0.0 once released you can verify.

**Comment by rajkumar14** [comment]
4.9.0.0 Released.
